[
    {
        "id": 101,
        "name": "User One",
        "gender": "Male",
        "mobile": "1234567890",
        "image": "user1.jpg",
        "birth_date": "1990-01-01T00:00:00.000Z",
        "country": 1,
        "state": 1,
        "firebase_token": "firebaseToken101",
        "steps": 1000,
        "followers": 50,
        "email": "user1@example.com",
        "achievement": 10,
        "referral_id": "referral101",
        "referral_count": 5,
        "password": "password1",
        "username": "username1",
        "account_status": "public",
        "education": "Bachelor's Degree",
        "location": "City A",
        "resume": "resume1.pdf",
        "student": "yes",
        "college": "College A",
        "university": "University A",
        "yearOfPassing": "2010",
        "monthOfPassing": "May"
    },
    {
        "id": 103,
        "name": "User Three",
        "gender": "Non-binary",
        "mobile": "1234567892",
        "image": "user3.jpg",
        "birth_date": "1992-03-03T00:00:00.000Z",
        "country": 3,
        "state": 3,
        "firebase_token": "firebaseToken103",
        "steps": 1200,
        "followers": 70,
        "email": "user3@example.com",
        "achievement": 30,
        "referral_id": "referral103",
        "referral_count": 7,
        "password": "password3",
        "username": "username3",
        "account_status": "public",
        "education": "PhD",
        "location": "City C",
        "resume": "resume3.pdf",
        "student": "yes",
        "college": "College C",
        "university": "University C",
        "yearOfPassing": "2015",
        "monthOfPassing": "July"
    },
    {
        "id": 105,
        "name": "User Five",
        "gender": "Female",
        "mobile": "1234567894",
        "image": "user5.jpg",
        "birth_date": "1994-05-05T00:00:00.000Z",
        "country": 5,
        "state": 5,
        "firebase_token": "firebaseToken105",
        "steps": 1400,
        "followers": 90,
        "email": "user5@example.com",
        "achievement": 50,
        "referral_id": "referral105",
        "referral_count": 9,
        "password": "password5",
        "username": "username5",
        "account_status": "public",
        "education": "Diploma",
        "location": "City E",
        "resume": "resume5.pdf",
        "student": "yes",
        "college": "College E",
        "university": "University E",
        "yearOfPassing": "2020",
        "monthOfPassing": "September"
    }
]